// Path: Assets/_Project/Scripts/Human/HumanGenerator.cs

using System.Collections.Generic;
using Core;
using Project.Human.Config;
using UnityEngine;

namespace Project.Human
{
    /// <summary>
    /// Responsible for generating human characters near houses with random configurations.
    /// Uses HumanManager and ObjectPool for performance.
    /// </summary>
    [DisallowMultipleComponent]
    public class HumanGenerator : MonoBehaviour
    {
        [Header("Generation Settings")]
        [SerializeField] private HumanConfig _config;
        [SerializeField] private bool _autoGenerateOnStart = true;
        [SerializeField] private float _generationDelay = 1f;
        [SerializeField] private int _maxHumansPerHouse = 3;
        [SerializeField] private float _minDistanceBetweenHumans = 1f;
        
        [Header("Batch Generation")]
        [SerializeField] private bool _useBatchGeneration = true;
        [SerializeField] private int _batchSize = 5;
        [SerializeField] private float _batchInterval = 0.5f;
        
        [Header("Debug")]
        [SerializeField] private bool _showDebugInfo = false;
        [SerializeField] private bool _logGenerationEvents = false;
        [SerializeField] private bool _drawSpawnGizmos = false;
        
        // Generation state
        private float _generationTimer = 0f;
        private float _batchTimer = 0f;
        private int _batchCounter = 0;
        private bool _isGenerating = false;
        
        // Cached references for performance
        private HumanManager _humanManager;
        private List<House> _availableHouses = new List<House>();
        
        /// <summary>
        /// Total number of humans generated by this generator.
        /// </summary>
        public int TotalGenerated { get; private set; }
        
        /// <summary>
        /// Whether the generator is currently active and generating humans.
        /// </summary>
        public bool IsGenerating => _isGenerating;
        
        #region Unity Lifecycle
        
        private void Awake()
        {
            // Cache references
            _humanManager = G.HumanManager;
            
            // Ensure we have a config
            if (_config == null)
                _config = G.HumanConfig;
            
            if (_showDebugInfo)
                Debug.Log($"[HumanGenerator] Initialized with config: {(_config != null ? _config.name : "null")}");
        }
        
        private void Start()
        {
            if (_autoGenerateOnStart)
            {
                StartGeneration();
            }
        }
        
        private void Update()
        {
            if (!_isGenerating)
                return;
            
            //UpdateGeneration(Time.deltaTime);
        }
        
        private void OnDrawGizmos()
        {
            if (!_drawSpawnGizmos || !Application.isPlaying)
                return;
            
            DrawSpawnGizmos();
        }
        
        #endregion
        
        #region Public API
        
        /// <summary>
        /// Start the human generation process.
        /// </summary>
        public void StartGeneration()
        {
            _isGenerating = true;
            _generationTimer = _generationDelay;
            _batchTimer = _batchInterval;
            _batchCounter = 0;
            
            // Refresh available houses
            RefreshAvailableHouses();

            UpdateGeneration(999);
            
            if (_logGenerationEvents)
                Debug.Log($"[HumanGenerator] Started generation with {_availableHouses.Count} available houses.");
        }
        
        /// <summary>
        /// Stop the human generation process.
        /// </summary>
        public void StopGeneration()
        {
            _isGenerating = false;
            
            if (_logGenerationEvents)
                Debug.Log("[HumanGenerator] Stopped generation.");
        }
        
        /// <summary>
        /// Generate a single human near a random available house.
        /// </summary>
        public HumanCharacter GenerateHuman()
        {
            if (_humanManager == null)
            {
                Debug.LogWarning("[HumanGenerator] HumanManager not available.");
                return null;
            }
            
            // Get a random house with capacity
            House house = GetRandomHouseWithCapacity();
            if (house == null)
            {
                if (_logGenerationEvents)
                    Debug.Log("[HumanGenerator] No houses with capacity available.");
                return null;
            }
            
            // Generate human data
            HumanData data = HumanData.CreateRandom(_config);
            
            // Spawn human via HumanManager
            HumanCharacter human = _humanManager.SpawnHuman(house, data);
            
            if (human != null)
            {
                TotalGenerated++;
                
                if (_logGenerationEvents)
                    Debug.Log($"[HumanGenerator] Generated human #{TotalGenerated} near house {house.HouseId}");
            }
            
            return human;
        }
        
        /// <summary>
        /// Generate multiple humans near houses.
        /// </summary>
        public List<HumanCharacter> GenerateHumans(int count)
        {
            List<HumanCharacter> generated = new List<HumanCharacter>();
            
            for (int i = 0; i < count; i++)
            {
                HumanCharacter human = GenerateHuman();
                if (human != null)
                    generated.Add(human);
                else
                    break; // No more capacity
            }
            
            return generated;
        }
        
        /// <summary>
        /// Generate humans for all houses to fill their capacity.
        /// </summary>
        public List<HumanCharacter> FillAllHouses()
        {
            List<HumanCharacter> generated = new List<HumanCharacter>();
            
            // Refresh house list
            RefreshAvailableHouses();
            
            foreach (House house in _availableHouses)
            {
                if (house == null)
                    continue;
                
                // Calculate how many humans to generate for this house
                int currentCount = _humanManager.GetHumanCountForHouse(house);
                int toGenerate = Mathf.Max(0, house.MaxResidents - currentCount);
                
                if (toGenerate > 0)
                {
                    List<HumanCharacter> houseHumans = _humanManager.SpawnHumans(house, toGenerate);
                    generated.AddRange(houseHumans);
                    TotalGenerated += houseHumans.Count;
                }
            }
            
            if (_logGenerationEvents)
                Debug.Log($"[HumanGenerator] Filled all houses, generated {generated.Count} humans.");
            
            return generated;
        }
        
        /// <summary>
        /// Refresh the list of available houses in the scene.
        /// </summary>
        public void RefreshAvailableHouses()
        {
            _availableHouses.Clear();
            
            // Find all houses in the scene
            House[] allHouses = FindObjectsOfType<House>();
            foreach (House house in allHouses)
            {
                if (house != null)
                    _availableHouses.Add(house);
            }
            
            if (_showDebugInfo)
                Debug.Log($"[HumanGenerator] Found {_availableHouses.Count} houses.");
        }
        
        #endregion
        
        #region Private Methods
        
        private void UpdateGeneration(float deltaTime)
        {
            if (_useBatchGeneration)
            {
                UpdateBatchGeneration(deltaTime);
            }
            else
            {
                UpdateSingleGeneration(deltaTime);
            }
        }
        
        private void UpdateSingleGeneration(float deltaTime)
        {
            _generationTimer -= deltaTime;
            
            if (_generationTimer <= 0f)
            {
                GenerateHuman();
                _generationTimer = _generationDelay;
            }
        }
        
        private void UpdateBatchGeneration(float deltaTime)
        {
            _batchTimer -= deltaTime;
            
            if (_batchTimer <= 0f)
            {
                // Generate a batch of humans
                int batchSize = Mathf.Min(_batchSize, GetAvailableCapacity());
                if (batchSize > 0)
                {
                    GenerateHumans(batchSize);
                    _batchCounter++;
                    
                    if (_logGenerationEvents)
                        Debug.Log($"[HumanGenerator] Generated batch #{_batchCounter} of {batchSize} humans.");
                }
                
                _batchTimer = _batchInterval;
            }
        }
        
        private House GetRandomHouseWithCapacity()
        {
            if (_availableHouses.Count == 0)
                return null;
            
            // Create a list of houses with capacity
            List<House> housesWithCapacity = new List<House>();
            foreach (House house in _availableHouses)
            {
                if (!_humanManager.IsHouseFull(house))
                    housesWithCapacity.Add(house);
            }
            
            if (housesWithCapacity.Count == 0)
                return null;
            
            // Return random house
            int randomIndex = Random.Range(0, housesWithCapacity.Count);
            return housesWithCapacity[randomIndex];
        }
        
        private int GetAvailableCapacity()
        {
            int totalCapacity = 0;
            
            foreach (House house in _availableHouses)
            {
                if (house == null)
                    continue;
                
                int currentCount = _humanManager.GetHumanCountForHouse(house);
                totalCapacity += Mathf.Max(0, house.MaxResidents - currentCount);
            }
            
            return totalCapacity;
        }
        
        private void DrawSpawnGizmos()
        {
            if (_availableHouses.Count == 0)
                return;
            
            Gizmos.color = Color.green;
            
            foreach (House house in _availableHouses)
            {
                if (house == null)
                    continue;
                
                // Draw house spawn radius
                Gizmos.DrawWireSphere(house.transform.position, house.SpawnRadius);
                
                // Draw capacity indicator
                int currentCount = _humanManager?.GetHumanCountForHouse(house) ?? 0;
                float fillRatio = (float)currentCount / house.MaxResidents;
                
                Gizmos.color = fillRatio >= 1f ? Color.red : 
                              fillRatio >= 0.7f ? Color.yellow : Color.green;
                
                Vector3 labelPos = house.transform.position + Vector3.up * 0.5f;
#if UNITY_EDITOR
                UnityEditor.Handles.Label(labelPos, $"{currentCount}/{house.MaxResidents}");
#endif
            }
        }
        
        #endregion
        
        #region Editor Helpers
        
#if UNITY_EDITOR
        [ContextMenu("Generate Single Human")]
        private void GenerateSingleHumanEditor()
        {
            if (!Application.isPlaying)
            {
                Debug.LogWarning("[HumanGenerator] Generation only works in Play mode.");
                return;
            }
            
            GenerateHuman();
        }
        
        [ContextMenu("Generate Batch (5 Humans)")]
        private void GenerateBatchEditor()
        {
            if (!Application.isPlaying)
            {
                Debug.LogWarning("[HumanGenerator] Generation only works in Play mode.");
                return;
            }
            
            GenerateHumans(5);
        }
        
        [ContextMenu("Fill All Houses")]
        private void FillAllHousesEditor()
        {
            if (!Application.isPlaying)
            {
                Debug.LogWarning("[HumanGenerator] Generation only works in Play mode.");
                return;
            }
            
            FillAllHouses();
        }
        
        [ContextMenu("Refresh House List")]
        private void RefreshHouseListEditor()
        {
            RefreshAvailableHouses();
            Debug.Log($"[HumanGenerator] Refreshed house list: {_availableHouses.Count} houses.");
        }
        
        [ContextMenu("Toggle Generation")]
        private void ToggleGenerationEditor()
        {
            if (!Application.isPlaying)
                return;
            
            if (_isGenerating)
                StopGeneration();
            else
                StartGeneration();
            
            Debug.Log($"[HumanGenerator] Generation {(IsGenerating ? "started" : "stopped")}.");
        }
#endif
        
        #endregion
    }
}